language: ruby
rvm:
  - 2.2.1
branches:
  only:
  - release
env:
  - secure: "OYmJyHKq/1aelmHw44WHUC0vGu4tlbCvUVm/JAykYYDUVrtGQdIdSppgxnntRW5ZT12TMcKNpv4ZUSSX4/RDnYveTK6WH0IorF3966YUY+Ko+e4jvW4/138lVU8nH5HzkfzFXdOACl2ltoxH4ZkGYzUaSWTsQmrp4bp/j4bnLBE="
script: ./scripts/build
after_success: ./scripts/deploy
